apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-svc-token
  namespace: cloudflared
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: cloudflared-svc-token
  dataFrom:
    - extract:
        key: cloudflared-svc