apiVersion: v1
kind: Namespace
metadata:
  name: metallb
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    gateway-access: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    gateway-access: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: envoy-gateway-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    gateway-access: "true"
  
