apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pubg-helper-location-db-secret
  namespace: pubg-helper
spec:
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: pubg-helper-db-secret
    creationPolicy: Merge
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: pubg-helper/db
        property: DATABASE_URL
