apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pubg-helper-postgres-secret
  namespace: pubg-helper
spec:
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: pubg-helper-db-secret
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: pubg-helper/db
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: pubg-helper/db
        property: POSTGRES_PASSWORD
    - secretKey: DATABASE_URL
      remoteRef:
        key: pubg-helper/db
        property: DATABASE_URL
