apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-eso-secret
  annotations:
    argocd.argoproj.io/sync-wave: "2" 
spec:
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: application-config
    template:
      type: kubernetes.io/dockerconfigjson # or TLS...
  dataFrom:
  - extract:
      key: database-credentials