apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: onprem-dev-storage-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/Steel-yong/Infra-gitops'
      revision: onprem-dev-test
      directories:
      - path: 'clusters/onprem-dev/longhorn'
  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: "7"
    spec:
      project: default
      source:
        repoURL: 'https://github.com/Steel-yong/Infra-gitops'
        targetRevision: onprem-dev-test
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
        retry:                    
          limit: 5
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 5m