apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: onprem-dev-gateway-system-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/Steel-yong/Infra-gitops
      revision: onprem-dev-test
      directories:
      - path: clusters/onprem-dev/envoy-gateway-system
  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: "17"
    spec:
      project: default
      sources:
        - repoURL: docker.io/envoyproxy
          chart: gateway-helm
          targetRevision: 1.7.1
          helm:
            valueFiles:
              - $values/clusters/onprem-dev/envoy-gateway-system/values.yaml
        - repoURL: https://github.com/Steel-yong/Infra-gitops
          targetRevision: onprem-dev-test
          path: clusters/onprem-dev/envoy-gateway-system
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: envoy-gateway-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 5m