apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - cluster-issuer.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.20.1
    releaseName: cert-manager
    namespace: cert-manager
    valuesInline: 
      crds:
        enabled: true
      replicaCount: 2
      global:
        priorityClassName: system-cluster-critical
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: cert-manager
              app.kubernetes.io/component: controller
      webhook:
        replicaCount: 2
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
        topologySpreadConstraints:
          - maxSkew: 2
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: cert-manager
                app.kubernetes.io/component: webhook
      cainjector:
        replicaCount: 2
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
        topologySpreadConstraints:
          - maxSkew: 2
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: cert-manager
                app.kubernetes.io/component: cainjector

