apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert
  namespace: pubg-helper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert
  template:
    metadata:
      labels:
        app: alert
    spec:
      containers:
        - name: alert
          image: harbor.yongun.shop/pubg-helper/alert:latest
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 5
