apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb
spec:
  addresses:
    - 0.0.0.0/32 
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-l2-adv
  namespace: metallb
spec:
  ipAddressPools:
    - main-pool