apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../components/metallb/crd
  - ../../../components/metallb/main

namespace: metallb

patches:
  - target:
      group: metallb.io
      version: v1beta1
      kind: IPAddressPool
      name: main-pool
    patch: |-
      - op: replace
        path: /spec/addresses
        value:
          - 172.20.0.200-172.20.0.220
