apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../components/metallb

namespace: metallb

patches:
  - target:
      group: metallb.io
      version: v1beta1
      kind: IPAddressPool
      name: infra-pool
    patch: |-
      - op: replace
        path: /spec/addresses
        value:
          - 172.20.0.100-172.20.0.120

  - target:
      group: metallb.io
      version: v1beta1
      kind: IPAddressPool
      name: dynamic-pool
    patch: |-
      - op: replace
        path: /spec/addresses
        value:
          - 172.20.0.200-172.20.0.220

  - target:
      kind: Deployment
      name: metallb-controller
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/topologySpreadConstraints
        value:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: metallb
                app.kubernetes.io/component: controller