apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-encryption-secret
  namespace: harbor
spec:
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: harbor-encryption-secret
  dataFrom:
    - extract:
        conversionStrategy: Default	
        decodingStrategy: None
        key: harbor-encryption
        metadataPolicy: None