namespaceOverride: monitoring

crds:
  enabled: true

defaultRules:
  create: true
  rules:
    kubeProxy: false        
    windows: false         

prometheus-windows-exporter:
  prometheus:
    monitor:
      enabled: false

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

  config:
    global:
      resolve_timeout: 5m
    inhibit_rules:
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'
    route:
      group_by: ['namespace', 'alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - receiver: 'null'
        matchers:
          - alertname = "Watchdog"
    receivers:
    - name: 'null'


grafana:
  replicas: 1
  grafana.ini:
    dashboards:
      default_home_dashboard_path: /tmp/dashboards/k8s-cluster.json
      annotations:
        grafana_folder: "Kubernetes"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
  admin:
    existingSecret: "grafana-admin-secret"
    userKey: admin-user
    passwordKey: admin-password
  defaultDashboardsTimezone: browser
  additionalDataSources: []
  # 나중에 추가:
  # - name: Loki
  #   type: loki
  #   url: http://loki-gateway.monitoring.svc.cluster.local
  #   access: proxy
  # - name: Tempo
  #   type: tempo
  #   url: http://tempo.monitoring.svc.cluster.local:3100
  #   access: proxy

prometheus:
  enabled: true
  prometheusSpec:
    retention: 10d
    retentionSize: "10GB"

    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi

    # 모든 네임스페이스의 ServiceMonitor 감지
    # false = 전체 네임스페이스 감지
    # true = 같은 네임스페이스만 감지
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false

prometheus-node-exporter:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

  tolerations:
    # master 노드에도 뜨게 설정
    - operator: Exists

kube-state-metrics:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

kubeControllerManager:
  enabled: true
  endpoints:
    - 172.20.0.10  

kubeEtcd:
  enabled: true
  endpoints:
    - 172.20.0.10  

kubeScheduler:
  enabled: true
  endpoints:
    - 172.20.0.10 

kubeProxy:
  enabled: false
