apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 9.4.16
    releaseName: argocd
    namespace: argocd
    valuesInline:
      configs:
        cm:
          kustomize.buildOptions: "--enable-helm --load-restrictor=LoadRestrictionsNone"
      
      server:
        service:
          type: ClusterIP
        extraArgs:
          - --insecure 

      controller:
        statusProcessors: 30 
        operationProcessors: 15 

      redis:
        resources:
          limits:
            cpu: 200m
            memory: 128Mi