apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.15.3
    releaseName: metallb-crd
    namespace: metallb
    valuesInline:
      namespaceOverride: "metallb" 
      crds:
        enabled: true
      controller:
        enabled: false
      speaker:
        enabled: false
    
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-5"