apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-dockerhub-repo
  namespace: argocd
spec:
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: argocd-dockerhub-repo
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: helm
        url: docker.io
        username: "{{ .username }}"
        password: "{{ .password }}"
        enableOCI: "true"
  dataFrom:
    - extract:
        conversionStrategy: Default	
        decodingStrategy: None
        key: dockerhub
        metadataPolicy: None